### ISSUE TITLE
Build planner

### ISSUE THREAD

**Issue by xmelissax** [AlyxMoon/lunar-pc-build-sim-companion#1]
I dont see anything at the build planner

**Comment by AlyxMoon** [comment]
Ah yes, you're right. Those pages are blank for now as I haven't put in that functionality. I should at least indicate those pages are in development to avoid confusion. Sorry about that!

**Comment by xmelissax** [comment]
Thank you for your fast reaction seeing forward to see those pages working

**Comment by AlyxMoon** [comment]
For now I've hidden them from the navbar. The implementation will come someday.
